package com.derwe.parent.model;

public enum TipoNotificacion {
    INVITACION_RECIBIDA,
    INVITACION_ACEPTADA,
    ACTIVIDAD_CREADA,
    ACTIVIDAD_EDITADA,
    ACTIVIDAD_ELIMINADA,
    ACTIVIDAD_PENDIENTE_APROBACION,
    SOLICITUD_CAMBIO_CUSTODIA,
    CAMBIO_CUSTODIA_APROBADO,
    CAMBIO_CUSTODIA_RECHAZADO
}
